version: "3.9"

services:
  video_converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: ["./convert.sh"]
    # Comportamento padrão ao rodar docker compose up
    command: ["sample.mp4", "avi"]
